# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Deploy to EdgeServer

on:
  push:
    branches:
      - "master"

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2
        with:
          version: 7.3.0

      - uses: actions/setup-node@v2
        with:
          node-version: "16.11.0"
          registry-url: "https://registry.npmjs.org"

      - run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Edgeserver Upload
        uses: lvkdotsh/edgeserver-upload@master
        with:
          app_id: "63746842118066176"
          server: https://api.edgeserver.io
          token: ${{ secrets.EDGESERVER_TOKEN }}
          directory: src
